companyDiet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
]

users/urls.py
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static
# from django_apscheduler import urls as apscheduler_urls
app_name = "user"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view,name="logout"),
    path("signup", views.signup_view, name="signup"),
    path('decision/', views.salad_decision, name='decision'),
    path('diet/',views.profile,name="diet"),
    path('editdiet/', views.upload,name="editdiet"),
    path('editdiet_create/', views.upload_create,name="editdiet_create"),
    # path('apscheduler/', include(apscheduler_urls)),
    
]

urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    user_id = models.CharField(max_length=10)
    is_salad = models.BooleanField(default=False)
    choice_date = models.DateField(auto_now=True)

class Profile(models.Model):
    title = models.CharField(max_length=25)
    image = models.ImageField(upload_to='images/')
    upload_date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.title

users/forms.py
from django import forms
from datetime import datetime,timedelta


now = datetime.now().date()

class SaladForm(forms.Form):
    CHOICES = [
        (True, '샐러드 먹기'),
        (False, '샐러드 안 먹기'),
    ]
           
    choice = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
import datetime as dt 
from .models import Profile

User = get_user_model()

def login_view(request):
    
    if request.method == "POST":
        username=request.POST["username"]
        password = request.POST["password"] 
        user= authenticate(username=username, password=password)
        if user is not None:
            print("GOOD")
            login(request, user)
            
        else:
            print("not good")        
    
    return render(request, "user/login.html")


def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view (request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        
        
        hashed_password = make_password(password)  # 비밀번호 암호화
        
        user = User.objects.create(username=username, password=hashed_password, email=email)
        user.firstname = firstname
        user.lastname = lastname

        user.save()
        return redirect("user:login")
    return render(request, "user/signup.html")

from .forms import SaladForm

def salad_decision(request):
    Users_is_salad = User.objects.values_list('is_salad')
    Users_username = User.objects.values_list('username')
    Users_choice_date = User.objects.values_list('choice_date')
    users = User.objects.all()
    now = dt.datetime.now()
    only_date = now.date()
    if request.method == 'POST':
        salad_choice = request.POST.get('salad_choice')
        
    
        print(Users_is_salad)
        print(Users_username)
        print(Users_choice_date)
        print(only_date)
        
    
        # print(now)
        if salad_choice == 'yes':
            if request.user.is_authenticated:
                user = User.objects.get(pk=request.user.pk)
                user.is_salad = True
                user.save()
                Users = User.objects.all()
                # user.choice_date = now
                print(Users_is_salad)
                print(Users_username)
                print(User.objects.all())
                
            return redirect("user:decision")
        elif salad_choice == 'no':
            if request.user.is_authenticated:
                user = User.objects.get(pk=request.user.pk)
                user.is_salad = False
                # user.choice_date = now
                user.save()
                
                
                print(Users_is_salad)
                print(Users_username)
                print(User.objects.all())
            return redirect("user:decision")
    return render(request, 'user/decision.html',{'users': users, 'now':only_date})

def profile(request):
    
    profile=Profile.objects.last()
    print(Profile.objects.values_list('upload_date'))
    return render(request,'user/diet.html',{'profile':profile})

def upload(request):
    return render(request, 'user/editdiet.html')

def upload_create(request):
    form=Profile()
    form.title=request.POST['title']
    try:
        form.image=request.FILES['image']
    except: 
        pass
    Profile.objects.all().delete()
    form.save()
    return redirect('user:diet')   

users/templates/user/decision.html
<!DOCTYPE html>
<html>
<head>
  <title>샐러드 선택</title>
</head>
<body>
  <h1>샐러드 선택</h1>
  <form method="POST">
    {% csrf_token %}
    <label for="salad_schoice">샐러드를 먹을까요?</label>
    <input type="radio" id="salad_choice_yes" name="salad_choice" value="yes" required>
    <label for="salad_choice_yes">예</label>
    <input type="radio" id="salad_choice_no" name="salad_choice" value="no" required>
    <label for="salad_choice_no">아니오</label>
    <button type="submit">선택</button>
  </form>

  <div>
    <ul> 
      {% for usr in users %}
        {% if usr.choice_date == now %}
          
          <li>{{ usr.username }} 님의 샐러드 먹는지 여부: {{ usr.is_salad }}</li>
        {% endif%}
      {% endfor %}
    </ul>
  </div>
  <a href="{% url 'user:login'%}">메인페이지</a>

</body>
</html>

users/templates/user/diet.html
<!DOCTYPE html>
<html>
<head>
  <title>식단보기</title>
</head>
<body>
  
    <h1> {{profile.title}} </h1> 
    <img src="{{ profile.image.url }}">
    <br><br>
  
  <a href="{% url 'user:editdiet'%}">식단편집</a>
  <a href="{% url 'user:login'%}">메인페이지</a>

</body>
</html>

users/templates/user/editdiet.html
<form action="{% url 'user:editdiet_create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    제목 <br>
    <input type="text" name="title"> <br>
    내용 <br>
    <input type="file" name="image"><br>
    <input type="submit" value="Submit" />
</form>

users/templates/user/login.html
로그인 페이지입니다.

<br>
{% if user.is_authenticated %}
    로그인 성공 
    {{ user.username }} 님 반갑습니다.
    
    <a href="{% url 'user:logout'%}">로그아웃</a>
    <a href="{% url 'user:decision' %}">샐러드</a>
    <a href="{% url 'user:diet' %}">식단보기</a>

    
    
{% else %}

<form action="" method="POST">
    {% csrf_token %} 
    <input name="username" type="text">
    <input name="password" type="password">
    <input type="submit" value="로그인">
</form>
<a href="{% url 'user:signup' %}">회원가입</a>

{% endif%}

users/templates/user/signup.html
회원가입 페이지

<br>

<form action="", method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name="username" type="text">
    <p>비밀번호</p>
    <input name="password" type="password">
    <p>성</p>
    <input name="firstname" type="text">
    <p>이름</p>
    <input name="lastname" type="text">
    <p>이메일</p>
    <input name="email" type="text">
    
    
    <input type="submit" value="회원가입">
</form>